openapi: 3.0.0
info:
  title: BFF API
  version: "1.0"
servers:
  - url: /web-api
paths:
  /users/login:
    post:
      summary: Logs in a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: Successful login
          content:
            text/plain:
              schema:
                type: string
                description: JWT token
  /bundles:
    get:
      summary: List available bundles
      responses:
        200:
          description: A list of bundles
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    bundleId:
                      type: string
                    title:
                      type: string
                    description:
                      type: string
                    products:
                      type: array
                      items:
                        type: object
                        properties:
                          productId:
                            type: string
                          title:
                            type: string
  /bundles/activate:
    post:
      summary: Activate a bundle for a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - userId
                - bundleId
              properties:
                userId:
                  type: string
                bundleId:
                  type: string
      responses:
        202:
          description: Bundle activation accepted
